Machine Learning Final Project: mate_learning.MateFinder Class Reference
mate_learning.MateFinder Class Reference
Used for the particular binary classification problem based on mates (usually groups of 2 - pairs) across each component of a discrete-valued data set.
Public Member Functions
def __init__
Constructor for the PairFinder object out of the given data set.
def validate_groupings
It removes overlapping groupings (matings) among the list of groupings provided.
def learn_by_mate_discovery
Brute force discovery of mates and relevant components during the training phase so that accuracy is the highest among all possibilities.
def select_K_components
Find the k number of components that produce the highest prediction accuracy from the training procedure:
def get_address
Resolves the address in the training LUT pertaining the given matings (a list of candidate matches) on the data set portion provided.
def get_index_address_table
This is a vectorized function that resolves the index (a.k.a.
def generate_decision_rules_LUT
A decision rules are learned from the provided list of matings (non-overlapping groups) and the chosen components.
def compute_prediction_accuracy
The accuracy of correct classification using the provided decision rules is computed statistically.
def predict_category
With the given list of matings (groupings) and the decision rules table, the list of measurement vectors (instances) are classified accordingly.
Public Attributes
all_data
all_classes
num_of_instances
num_of_components
num_of_values
mating_size
num_of_mating_groups
map_base
class_learning
class_test
feat_data_learning_train
class_learning_train
feat_data_learning_validate
class_learning_validate
N_train
c0_indices_train
c1_indices_train
feat_train_c0
feat_train_c1
values_list
mates_candidates_per_component
address_multiples
Private Member Functions
def _generate_training_LUT
Generates an empty look-up table that will be addressed to train the learned with the given data.
Detailed Description
Used for the particular binary classification problem based on mates (usually groups of 2 - pairs) across each component of a discrete-valued data set.
This class provides procedures such as the removal of irrelevant components (selection of relevant components), as well as essential learning (training and validation) and testing procedures from learned decision tables of pairs.
Once a MateFinder object has been instantiated through the constructor, the interfacing methods employed by an external classifier are: learn_by_mate_discovery() and compute_prediction_accuracy()
Definition at line 28 of file mate_learning.py.
Constructor & Destructor Documentation
def mate_learning.MateFinder.__init__ (self, component_data, classification_labels, mating_size = 2)
Constructor for the PairFinder object out of the given data set.
: The data set (and corresponing classification labels) are split into the following portions: 50% for learning phase: 25% training + 25% validation 50% for testing phase: the real test using the learned table of decision rules
This constructor initializes the reusable member variables that are called from other functions.
Parameters
component_data A 2D matrix (numpy ndarray) of measurements (observations) to work with. A copy is created of this.
classification_labels The category classification_labels as a 1D ndarray. Expected to be nonnegative integers
mating_size It should default to 2 (for pairs), but as in life, mating (a.k.a grouping) can be done using larger number of members. Note, the number of values (10 digits for this exercise) must be divisible by the mating_size. For now, we basically can have only groups of 2 or 5.
Definition at line 45 of file mate_learning.py.
Member Function Documentation
def mate_learning.MateFinder._generate_training_LUT (self, cols) private
Generates an empty look-up table that will be addressed to train the learned with the given data.
Parameters
cols the number of columns (components) in the data set that are being used for the training.
Returns
: An empty 2-dimensional matrix that can be addressed while performing decision statistics
Definition at line 201 of file mate_learning.py.
References mate_learning.MateFinder.num_of_mating_groups.
Referenced by mate_learning.MateFinder.generate_decision_rules_LUT().
def mate_learning.MateFinder.compute_prediction_accuracy (self, matings, decisions_LUT, relevant_components = None, comp_data_test = None, class_test = None, verbose = False)
The accuracy of correct classification using the provided decision rules is computed statistically.
Parameters
matings An ordered list of indices used to group employing the map_based of choice set in the constructor. By default, the mapping is pair-wise ordered from left to right.
decisions_LUT The learned rules in a LUT
relevant_components By default is set to None, so all components will be used. Otherwise, this specifies the selection of components to work with.
comp_data_test If any, this is the component data set to use for predicting upon and testing the classification accuracy with the provided matings and decision rules. Otherwise, it defaults to using the test data set (the 50% of the entire data set passed in the constructor)
class_test The classification labels associated with comp_data_test if any.
verbose Indicates whether to enable message verbosity.
Returns
: The normalized accuracy of correct classification computed according to the specified parameters.
Definition at line 293 of file mate_learning.py.
References mate_learning.MateFinder.class_test, and mate_learning.MateFinder.predict_category().
Referenced by mate_learning.MateFinder.select_K_components().
def mate_learning.MateFinder.generate_decision_rules_LUT (self, matings, comp_subset)
A decision rules are learned from the provided list of matings (non-overlapping groups) and the chosen components.
Parameters
matings An ordered list of indices used to group employing the map_based of choice set in the constructor. By default, the mapping is pair-wise ordered from left to right.
comp_subset The list of selected component indices upon where the decision table is generated
Returns
: The 1-D table of decision rules extracted from frequency analysis out of the learning portion of the data set
Definition at line 255 of file mate_learning.py.
References mate_learning.MateFinder._generate_training_LUT(), mate_learning.MateFinder.feat_train_c0, mate_learning.MateFinder.feat_train_c1, mate_learning.MateFinder.get_address(), mate_learning.MateFinder.get_index_address_table(), and mate_learning.MateFinder.N_train.
Referenced by mate_learning.MateFinder.learn_by_mate_discovery(), and mate_learning.MateFinder.select_K_components().
def mate_learning.MateFinder.get_address (self, matings, component_data)
Resolves the address in the training LUT pertaining the given matings (a list of candidate matches) on the data set portion provided.
Parameters
matings List of indices associated with the groupings (matches)
component_data The ndarray of component data for which addresses are resolved for
Returns
: the numpy n-dimensional array of resolved addresses for the provided data and desired matings
Definition at line 215 of file mate_learning.py.
References mate_learning.MateFinder.map_base, and mate_learning.MateFinder.values_list.
Referenced by mate_learning.MateFinder.generate_decision_rules_LUT(), and mate_learning.MateFinder.predict_category().
def mate_learning.MateFinder.get_index_address_table (self, address)
This is a vectorized function that resolves the index (a.k.a.
hash address) on the 1-D array of rules employing in the learning/testing procedure).
Parameters
address An array of address arrays to be hashed for on a 1-D table using the pertaining base (such as base 5 when dealing with groups of 2)
Returns
: the resolved 1-D array of indices corresponding the input address.
Definition at line 241 of file mate_learning.py.
References mate_learning.MateFinder.address_multiples.
Referenced by mate_learning.MateFinder.generate_decision_rules_LUT(), and mate_learning.MateFinder.predict_category().
def mate_learning.MateFinder.learn_by_mate_discovery (self)
Brute force discovery of mates and relevant components during the training phase so that accuracy is the highest among all possibilities.
Returns
The 1-d numpy array (table) of learned rules.
List of best combination of mates (pairs) across the discovered relevant components
The list of discovered relevant components from the training phase
Definition at line 120 of file mate_learning.py.
References mate_learning.MateFinder.generate_decision_rules_LUT(), mate_learning.MateFinder.num_of_components, and mate_learning.MateFinder.select_K_components().
def mate_learning.MateFinder.predict_category (self, matings, decisions_LUT, instance_vector)
With the given list of matings (groupings) and the decision rules table, the list of measurement vectors (instances) are classified accordingly.
Parameters
matings An ordered list of indices used to group employing the map_based of choice set in the constructor. By default, the mapping is pair-wise ordered from left to right.
decisions_LUT The learned rules in a LUT
instance_vector The list of measurement vectors (instances, a.k.a observations) to classify.
Returns
: The classification results corresponding to the supplied instance vectors for the specified rules and matings.
Definition at line 325 of file mate_learning.py.
References mate_learning.MateFinder.get_address(), and mate_learning.MateFinder.get_index_address_table().
Referenced by mate_learning.MateFinder.compute_prediction_accuracy().
def mate_learning.MateFinder.select_K_components (self, k_comps, verbose = True)
Find the k number of components that produce the highest prediction accuracy from the training procedure:
Learning of rules is performed on the training portion of the data set (technically, the 25% of the entire data set) Accuracy validation to choose best is performed on the validation data set (technically, the other 25% of the entire data set)
Parameters
k_comps Indicates the number of components to be attempted the "brute-force" search upon.
Returns
The accuracy (normalized value from 0 to 1.0) obtained using the best selection of k components
List of best combination of mates (pairs) across the best selected components
The list of the best selected components
Definition at line 160 of file mate_learning.py.
References mate_learning.MateFinder.class_learning_validate, mate_learning.MateFinder.compute_prediction_accuracy(), mate_learning.MateFinder.feat_data_learning_validate, mate_learning.MateFinder.generate_decision_rules_LUT(), mate_learning.MateFinder.mates_candidates_per_component, and mate_learning.MateFinder.num_of_components.
Referenced by mate_learning.MateFinder.learn_by_mate_discovery().
def mate_learning.MateFinder.validate_groupings (self, candidate_lists)
It removes overlapping groupings (matings) among the list of groupings provided.
Parameters
candidate_lists An ndarray of all possible groupings (in our particular exercise, these are all possible combinations of 2 out of 10 digits)
Returns
: the filtered list of non-overlapping groupings. The reduction in length for this list is crucial for faster results during learning procedure.
Definition at line 96 of file mate_learning.py.
Member Data Documentation
mate_learning.MateFinder.address_multiples
Definition at line 85 of file mate_learning.py.
Referenced by mate_learning.MateFinder.get_index_address_table().
mate_learning.MateFinder.all_classes
Definition at line 48 of file mate_learning.py.
mate_learning.MateFinder.all_data
Definition at line 47 of file mate_learning.py.
mate_learning.MateFinder.c0_indices_train
Definition at line 70 of file mate_learning.py.
mate_learning.MateFinder.c1_indices_train
Definition at line 71 of file mate_learning.py.
mate_learning.MateFinder.class_learning
Definition at line 59 of file mate_learning.py.
mate_learning.MateFinder.class_learning_train
Definition at line 64 of file mate_learning.py.
mate_learning.MateFinder.class_learning_validate
Definition at line 66 of file mate_learning.py.
Referenced by mate_learning.MateFinder.select_K_components().
mate_learning.MateFinder.class_test
Definition at line 60 of file mate_learning.py.
Referenced by mate_learning.MateFinder.compute_prediction_accuracy().
mate_learning.MateFinder.feat_data_learning_train
Definition at line 63 of file mate_learning.py.
mate_learning.MateFinder.feat_data_learning_validate
Definition at line 65 of file mate_learning.py.
Referenced by mate_learning.MateFinder.select_K_components().
mate_learning.MateFinder.feat_train_c0
Definition at line 72 of file mate_learning.py.
Referenced by mate_learning.MateFinder.generate_decision_rules_LUT().
mate_learning.MateFinder.feat_train_c1
Definition at line 73 of file mate_learning.py.
Referenced by mate_learning.MateFinder.generate_decision_rules_LUT().
mate_learning.MateFinder.map_base
Definition at line 54 of file mate_learning.py.
Referenced by mate_learning.MateFinder.get_address().
mate_learning.MateFinder.mates_candidates_per_component
Definition at line 82 of file mate_learning.py.
Referenced by mate_learning.MateFinder.select_K_components().
mate_learning.MateFinder.mating_size
Definition at line 52 of file mate_learning.py.
mate_learning.MateFinder.N_train
Definition at line 67 of file mate_learning.py.
Referenced by mate_learning.MateFinder.generate_decision_rules_LUT().
mate_learning.MateFinder.num_of_components
Definition at line 50 of file mate_learning.py.
Referenced by mate_learning.MateFinder.learn_by_mate_discovery(), and mate_learning.MateFinder.select_K_components().
mate_learning.MateFinder.num_of_instances
Definition at line 49 of file mate_learning.py.
mate_learning.MateFinder.num_of_mating_groups
Definition at line 53 of file mate_learning.py.
Referenced by mate_learning.MateFinder._generate_training_LUT().
mate_learning.MateFinder.num_of_values
Definition at line 51 of file mate_learning.py.
mate_learning.MateFinder.values_list
Definition at line 78 of file mate_learning.py.
Referenced by mate_learning.MateFinder.get_address().
The documentation for this class was generated from the following file:
mate_learning.py