Machine Learning Final Project: learning_driver Namespace Reference
learning_driver Namespace Reference
Functions
def learn_model_naive_bayes
Simple training (fitting) of the data set using the Naive Bayesian classifier.
def classify_dataset
Reads the data set from the file name provided in order to perform learning and final classification test providing the resulting accuracy of correct classification.
Variables
string data_file_prefix = "dataset-3rel_components-quantized_butterfly-2014-12-27"
test_against_MNB = False
Function Documentation
def learning_driver.classify_dataset (data_file_prefix, load_data_from_pickle = False)
Reads the data set from the file name provided in order to perform learning and final classification test providing the resulting accuracy of correct classification.
Parameters
data_file_prefix The prefix of the data set file name
load_data_from_pickle When set to True, a Python pickle (.pkl extension) will be used instead of the traditional comma separated valued (.csv extension) data set.
Definition at line 56 of file learning_driver.py.
References common_tools.load_dataset_from_pickle(), common_tools.read_data(), and common_tools.save_dataset_to_pickle().
def learning_driver.learn_model_naive_bayes (data_file_prefix, delimiter = ", percentage_to_train = 90)
Simple training (fitting) of the data set using the Naive Bayesian classifier.
Parameters
filename the database filename path
porcentage_to_train The percentage from the database dedicated for training. The complimentary percentage is used for testing.
Definition at line 24 of file learning_driver.py.
References common_tools.read_data().
Variable Documentation
string learning_driver.data_file_prefix = "dataset-3rel_components-quantized_butterfly-2014-12-27"
Definition at line 86 of file learning_driver.py.
learning_driver.test_against_MNB = False
Definition at line 88 of file learning_driver.py.