Machine Learning Final Project: common_tools Namespace Reference
common_tools Namespace Reference
Functions
def get_namestr
Finds and returns the variable name for the object instance in question in the desired namespace.
def save_obj_in_pickle
def load_obj_from_pickle
def save_dataset_to_pickle
def load_dataset_from_pickle
def read_data
def filter_irrelevant_features
def pdf
def reverse_axis_elems
def rms
def nanrms
If you have nans in your data, you can do.
def weighted_avg_and_std
Return the weighted average and standard deviation.
def mean_and_std
Return the arithmetic mean or unweighted average and the standard deviation.
Function Documentation
def common_tools.filter_irrelevant_features (feature_data, labels, wanted_num_of_features, use_chi2 = True)
Parameters
use_sklearn Indicates whether the filtering is done with scikit-learn's SelectKBesr or a custom bruteforce procedure.
Definition at line 110 of file common_tools.py.
def common_tools.get_namestr (obj, namespace)
Finds and returns the variable name for the object instance in question in the desired namespace.
For example
>>> get_namestr(my_wow, globals())
Out: 'my_wow'
Definition at line 23 of file common_tools.py.
Referenced by load_obj_from_pickle(), and save_obj_in_pickle().
def common_tools.load_dataset_from_pickle (filename_prefix)
Definition at line 51 of file common_tools.py.
References load_obj_from_pickle().
Referenced by learning_driver.classify_dataset().
def common_tools.load_obj_from_pickle (filename, namespace = None)
Definition at line 40 of file common_tools.py.
References get_namestr().
Referenced by load_dataset_from_pickle().
def common_tools.mean_and_std (values)
Return the arithmetic mean or unweighted average and the standard deviation.
Parameters
values Numpy ndarrays of values
Definition at line 170 of file common_tools.py.
def common_tools.nanrms (x, axis = None)
If you have nans in your data, you can do.
Definition at line 150 of file common_tools.py.
def common_tools.pdf (point, cons, mean, det_sigma)
Definition at line 123 of file common_tools.py.
def common_tools.read_data (filename, delimiter = ", feature_indices = None, use_string_labels = True, given_string_labels = False, num_components = 10, dtype = 'uint8', has_header = True, shuffle_rows = False)
Parameters
filename the database filename path
delimiter the string usefile delimeter (e.g. ",")
feature_indices The index of the columns for the desired indices. If nothing is passed, then all features are used.
use_string_labels indicates whether labels are kept as strings, or if False, they should be indexed instead
given_string_labels indicates whether class labels are strings. Use False (default) to imply the use of digit labels
num_components number of columns (feature dimensions) in the file.
Returns
the np array of features and the single-column array of the labels from the dataset being read.
Definition at line 65 of file common_tools.py.
Referenced by learning_driver.classify_dataset(), and learning_driver.learn_model_naive_bayes().
def common_tools.reverse_axis_elems (arr, k = 0)
Parameters
arr the numpy ndarray to be reversed
k The axis to be reversed Reverse the order of rows: set axis k=0 Reverse the order of columns: set axis k=1
Returns
: the reversed numpy array
Definition at line 138 of file common_tools.py.
def common_tools.rms (x, axis = None)
Definition at line 142 of file common_tools.py.
def common_tools.save_dataset_to_pickle (all_features_data, all_classes, filename_prefix)
Definition at line 48 of file common_tools.py.
References save_obj_in_pickle().
Referenced by learning_driver.classify_dataset().
def common_tools.save_obj_in_pickle (obj_instance, filename, namespace = None)
Definition at line 33 of file common_tools.py.
References get_namestr().
Referenced by save_dataset_to_pickle().
def common_tools.weighted_avg_and_std (values, weights)
Return the weighted average and standard deviation.
values, weights – Numpy ndarrays with the same shape.
Definition at line 159 of file common_tools.py.